FinalDatLong/Areas/Admin/Controllers/AcceptBookingController.cs
using FinalDatLong.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using System.IO;
using System.Data.Entity.Migrations;
using System.Drawing;
using SachOnline;
using System.Net.Mail;
using System.Net;

namespace FinalDatLong.Areas.Admin.Controllers
{
    public class AcceptBookingController : Controller
    {
        // GET: Admin/Booking
        Model1 db = new Model1();
        public ActionResult Index(int ? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            return View(db.Booking.ToList().OrderBy(n => n.IDBooking).ToPagedList(iPageNum, iPageSize));
        }
        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Booking model)
        {

            if (ModelState.IsValid)
            {
                db.Booking.AddOrUpdate(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Accept(int id)
        {
            var booking = db.Booking.FirstOrDefault(n => n.IDBooking == id);

            if (booking != null)
            {
                booking.Accept = true;
                db.SaveChanges();

               SendBookingConfirmationEmail(booking.Patient.Email, true);

            }
            else
            {
                ViewBag.Error = "Error";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Refuse(int id)
        {
            var booking = db.Booking.FirstOrDefault(n => n.IDBooking == id);

            if (booking != null)
            {
                booking.Accept = false;
                db.SaveChanges();

               SendBookingConfirmationEmail(booking.Patient.Email, false);

            }
            else
            {
                ViewBag.Error = "Error";
            }

            return RedirectToAction("Index");
        }

        private void SendBookingConfirmationEmail(string patientEmail, bool accepted)
        {
            var subject = accepted ? "Booking Confirmation" : "Booking Refusal";
            var body = accepted ? "Your appointment has been successfully booked." : "Unfortunately, your appointment has been refused due to an emergency.";

            var mail = new SmtpClient("smtp.gmail.com", 587)
            {
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential("21280103e0017@student.tdmu.edu.vn", "sihi ngnu oipz plao"),
                EnableSsl = true,
            };

            var message = new MailMessage();
            message.From = new MailAddress("21280103e0017@student.tdmu.edu.vn");
            message.ReplyToList.Add("21280103e0017@student.tdmu.edu.vn");
            message.To.Add(new MailAddress(patientEmail));
            message.Subject = subject;
            message.Body = body;

            mail.Send(message);
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            Booking model = db.Booking.FirstOrDefault(n => n.IDBooking == id);
            model.Doctor = db.Doctor.FirstOrDefault(n => n.IDDoctor == model.IDDoctor);
            model.Patient = db.Patient.FirstOrDefault(n => n.IDPatient == model.IDPatient);
            return View(model);
        }
        [HttpPost]
        public ActionResult Detail(Booking model)
        {
            if (ModelState.IsValid)
            {
                db.Booking.AddOrUpdate(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

FinalDatLong/Areas/Admin/Views/AcceptBooking/Detail.cshtml
@model FinalDatLong.Models.Booking

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Detail</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Booking</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDBooking)

        <div class="form-group">
            @Html.LabelFor(model => model.IDPatient, "IDPatient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDPatient, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.IDPatient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDDoctor, "IDDoctor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDDoctor, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.IDDoctor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Accept, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Accept)
                    @Html.ValidationMessageFor(model => model.Accept, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", rows = 4 } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datetime, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
                @Html.ValidationMessageFor(model => model.Datetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinalDatLong/Areas/Admin/Views/AcceptBooking/Index.cshtml
@model IEnumerable<FinalDatLong.Models.Booking>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
           Doctor
        </th>
        <th>
            Patient
        </th>
        <th>
            Status
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Datetime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Doctor.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Patient.UserName)
        </td>
        <td>
            @if (item.Accept == true)
            {
                <span class="text-success">Accept</span>
            }
            else if (item.Accept == false)
            {
                <span class="text-danger">Refuse</span>
            }
            else
            {
            <span class="text-danger">Pending</span>
            }
            
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Datetime)
        </td>
        <td>
          
            @if (item.Accept != true)
            {
                <a href="@Url.Action("Accept","AcceptBooking", new {Area = "Admin", id = item.IDBooking})" class="btn btn-outline-primary">Accept</a>
            }
            else
            {
                <a href="@Url.Action("Refuse","AcceptBooking", new {Area = "Admin", id = item.IDBooking})" class="btn btn-outline-danger">Refuse</a>
            }
        <a href="@Url.Action("Detail","AcceptBooking", new { id = item.IDBooking })" class="btn btn-outline-warning"> Details</a>
        </td>
    </tr>
}

</table>