FinalDatLong/Models/Booking.cs
namespace FinalDatLong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Booking")]
    public partial class Booking
    {
        // bi loi lay c nay loi gi em IDBooking luc em tao ko tu dong tang 
        //Em chay 
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IDBooking { get; set; }


        public int? IDPatient { get; set; }

        public int? IDDoctor { get; set; }

        public bool Accept { get; set; }
        
        public string Description { get; set; }



        public DateTime? Datetime { get; set; }

        public virtual Doctor Doctor { get; set; }

        public virtual Patient Patient { get; set; }
    }
}

FinalDatLong/Controllers/BookingController.cs
using FinalDatLong.Models;
using SachOnline;
using System;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using System.Web.UI.WebControls;

namespace FinalDatLong.Controllers
{
    public class BookingController : Controller
    {
        // GET: Booking
        Model1 db = new Model1();
       
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Navbar()
        {
            return PartialView();
        }

        public ActionResult Footer()
        {
            return PartialView();
        }
        public ActionResult LayoutNavbar()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return PartialView();
        }
        public ActionResult NavbarDangNhap()
        {
            return PartialView();
        }
        public ActionResult SlideShow()
        {
            return PartialView();
        }
        public ActionResult Video()
        {
            return PartialView();
        }
        public ActionResult Card()
        {
            return PartialView();
        }
        public ActionResult NewBooking()
        {
            return PartialView();
        }
        //public ActionResult ProfileDoctor(int id)
        //{
        //    var doctor = db.Doctor.FirstOrDefault(n => n.IDDoctor == id);
        //    return PartialView(doctor);
        //}

        // em new booking o day 
        //Dung get o tren em khai bao get r ma thay => 2 phuong thuc cung get phai khac nhau ve ten pt hoac tham so
        //get
        //public ActionResult ProfileDoctor2(int id ,FormCollection f)
        //{
        //    //Em khai bao id ma khi goi truyen vao IDDoctor nen se ko goi method nay
        //    Booking Booking = new Booking();
        //    var doctor = db.Doctor.Find(id);

        //    if (doctor == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    if (Session["UserName"] != null)
        //    {
        //        var patient = (Patient)Session["UserName"];
        //        // Lấy thông tin hồ sơ từ cơ sở dữ liệu dựa trên IDPatient

        //        if (patient != null)
        //        {
        //            Booking.Patient = patient;
        //            Booking.IDPatient = patient.IDPatient;
        //        }
        //        else
        //        {
        //            return RedirectToAction("Error");
        //        }
        //    }

        //    Booking.IDDoctor = id;
        //    Booking.Doctor = doctor;

        //    if (ModelState.IsValid)
        //    {
        //        db.Booking.Add(Booking);
        //        db.SaveChanges();
        //    }
        //    return View();
        //}



        public static string ConverImageToBase64(string path)
        {
            using (Image image = Image.FromFile(path))
            {
                using (MemoryStream m = new MemoryStream())
                {
                    image.Save(m, image.RawFormat);
                    byte[] imageBytes = m.ToArray();

                    string base64String = "data:image/jpeg;base64," + Convert.ToBase64String(imageBytes);
                    return base64String;
                }
            }
        }


        public ActionResult PatientProfile()
        {

            if (Session["UserName"] != null)
            {
                var patient = (Patient)Session["UserName"];
                patient.MatKhauNL = patient.Password;

                if (patient != null)
                {
                    return View(patient);
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult PatientProfile(Patient model, HttpPostedFileBase myFile)
        {
           

            if (ModelState.IsValid)
            {


                if (myFile != null)
                {
                    Image img = Image.FromStream(myFile.InputStream, true, true);
                    model.Avatar = Utility.ConvertImageToBase64(img);
                }
               
                db.Patient.AddOrUpdate(model);
                db.SaveChanges();
                Session["UserName"] = model;
            }
            
            
            return View(model);
        }





    }
}

FinalDatLong/Controllers/SpecializationController.cs
using FinalDatLong.Models;
using SachOnline;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalDatLong.Controllers
{
    public class SpecializationController : Controller
    {
        //Xong roi em nhé  da ok em cam on thay nhieu 
        Model1 db = new Model1();
        // GET: Specialition
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult Khoa(string Khoa)
        {
            var listDoctor = from doctor in db.Doctor where doctor.Specialization == Khoa select doctor;
            return View(listDoctor);
        }
        public ActionResult ProfileDoctor(int Id)
        {
            Doctor doctor = db.Doctor.FirstOrDefault(d => d.IDDoctor == Id);
            return View(doctor);
        }
        
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Booking model, int id)
        {
            model.IDDoctor = id; //Gan id thoi con truong Doctor la cach de lay thong tin doctor vi trong CSDL cua ban ko co truong nay

            //model.Doctor = db.Doctor.FirstOrDefault(d => d.IDDoctor == id);
            ViewBag.doctor = db.Doctor.FirstOrDefault(d => d.IDDoctor == id);
            if (Session["UserName"] != null)
            {
                var patient = (Patient)Session["UserName"];
                // Lấy thông tin hồ sơ từ cơ sở dữ liệu dựa trên IDPatient

                if (patient != null)
                {
                    //model.Patient = patient;
                    model.IDPatient = patient.IDPatient;
                }
                else//em chay lai
                {
                    return RedirectToAction("Error");
                }
            }

            if (ModelState.IsValid)
            {
                db.Booking.Add(model);
                db.SaveChanges();
                //Em muon redirect ve action nao => _Layout la view shared ko phai action okem hieu r chay dc r a thay
                //Add thanh cong mon tra ve trang nao trang home them cai thong bao da dat he nthanh cong
                ViewBag.ThongBao = "Da dat thanh cong";
                return View(model); 
            }
            return View();
        }
    }
}

FinalDatLong/Views/Booking/Index.cshtml
@{
    ViewBag.Title = "Index";
}

FinalDatLong/Views/Booking/NewBooking.cshtml
<div>
    <a href="https://sonqb.com/media/2021/07/dich-vu-booking-pr-bao-sonqb.jpg" data-bs-toggle="modal" data-bs-target="#myModal">
        <img src="https://sonqb.com/media/2021/07/dich-vu-booking-pr-bao-sonqb.jpg" alt="..." class="img-fluid h-100">
    </a>
</div>

@*<form action="/Booking/newBooking" method="post">*@
    @*The Modal*@
    <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-dialog-scrollable modal-xxl">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h3 class="modal-title">Booking doctor</h3>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <form id="form1">
                        <div class="row">
                            <div class="col-5">
                                <h3>Specialize</h3>

                                <a style="text-decoration: none" href="@Url.Action("Khoa","Specialization", new { Khoa = "Đa khoa"})">
                                    <div class="row" style="color: black; font-size: x-large; padding: 20px 0 7px 0">
                                        <img style="width: 60px; height: 40px " src="https://cdn-healthcare.hellohealthgroup.com/specialties/da-khoa.png" />Đa khoa
                                    </div>
                                </a>
                                <a style="text-decoration: none" href="@Url.Action("Khoa","Specialization", new { Khoa = "Nha khoa"})">
                                    <div class="row" style="color: black; font-size: x-large; padding: 10px 0 7px 0 ">
                                        <img style="width:60px;height:40px" src="https://cdn-healthcare.hellohealthgroup.com/specialties/nha-khoa.png" />Nha khoa
                                    </div>
                                </a>
                                <a style="text-decoration: none" href="@Url.Action("Khoa","Specialization", new { Khoa = "Da lieu"})">
                                    <div class="row" style="color: black; font-size: x-large; padding: 10px 0 7px 0 ">
                                        <img style="width: 60px; height: 40px " src="https://cdn-healthcare.hellohealthgroup.com/specialties/da-lieu.png" />Da liễu
                                    </div>
                                </a>
                                <a style="text-decoration: none" href="@Url.Action("Khoa","Specialization", new { Khoa = "Nhãn khoa"})">
                                    <div class="row" style="color: black; font-size: x-large; padding: 10px 0 7px 0 ">
                                        <img style="width: 60px; height: 40px " src="https://cdn-healthcare.hellohealthgroup.com/2022/03/1648192921_623d6d99099d03.94959451.jpg" />Nhãn khoa
                                    </div>
                                </a>
                                <a style="text-decoration: none" href="@Url.Action("Khoa","Specialization", new { Khoa = "Phu khoa"})">
                                    <div class="row" style="color: black; font-size: x-large; padding: 10px 0 7px 0 ">
                                        <img style="width: 60px; height: 40px " src="https://cdn-healthcare.hellohealthgroup.com/specialties/san-phu-khoa.png" />Phụ khoa
                                    </div>
                                </a>
                                <a style="text-decoration: none;" href="@Url.Action("Khoa","Specialization", new { Khoa = "Cot song"})">
                                    <div class="row" style="color: black; font-size: x-large; padding: 10px 0 7px 0">
                                        <img style="width: 60px; height: 40px" src="https://cdn-healthcare.hellohealthgroup.com/2022/01/1643269107_61f24bf31bd9a1.55037235.png" />Trị liệu thần kinh cột sống
                                    </div>
                                </a>
                            </div>
                            <div class="col-7">
                                <div class="row">
                                    <h3 class="text-center">APPOINTMENT BOOKING</h3>
                                    <div class="row">
                                        <a style="color: #23A455;">
                                            Who are you scheduling for?
                                        </a>
                                        <div class="form-check col">
                                            <input class="form-check-input" type="radio" name="flexRadioDefault" id="forRelative">
                                            <label class="form-check-label" for="forRelative">
                                                Family Member
                                            </label>
                                        </div>
                                        <div class="form-check col">
                                            <input class="form-check-input" type="radio" name="flexRadioDefault" id="forSelf">
                                            <label class="form-check-label" for="forSelf">
                                                Yourself
                                            </label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <a style="color: #23A455">Full Name</a>
                                        <input type="text" class="form-control" aria-describedby="inputGroup-sizing-sm" />
                                    </div>
                                    <div class="row">
                                        <a style="color: #23A455">Phone Number</a>
                                        <input type="text" class="form-control" aria-describedby="inputGroup-sizing-sm" />
                                    </div>
                                    <div class="row">
                                        <a style="color: #23A455">Doctor's Name</a>
                                        <input type="text" class="form-control" aria-describedby="inputGroup-sizing-sm" />
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <a style="color: #23A455">Appointment Date</a>
                                            <input class="form-control" type="date" />
                                        </div>
                                        <div class="col">
                                            <a style="color: #23A455">Appointment Time</a>
                                            <input class="form-control" type="time" />
                                        </div>
                                    </div>
                                    <div class="row">
                                        <a style="color: #23A455">
                                            Symptoms/Reason for Appointment
                                        </a>
                                        <textarea name="symptoms-description" rows="4" cols="50"></textarea>
                                    </div>

                                    <div class="row">
                                        <div style="text-align:center; margin: 5% 0 0 0">
                                            <button class="btn success" onclick="myFunction()">Đặt lịch hẹn <i class="bi bi-calendar2-week"></i></button>
                                            <p id="demo"></p>
                                            <script>
                                                function myFunction() {
                                                    var txt;
                                                    if (confirm("Đặt hẹn thành công!")) {
                                                        txt = "You pressed OK!";
                                                    } else {
                                                        txt = "You pressed Cancel!";
                                                    }
                                                    document.getElementById("demo").innerHTML = txt;
                                                      }
                                            </script>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<form>

FinalDatLong/Views/Booking/PatientProfile.cshtml
@model FinalDatLong.Models.Patient
@{
    ViewBag.Title = "PatientProfile";
    Layout = "~/Views/Shared/LayoutNavbar.cshtml";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<script src="~/Scripts/popper.min.js"></script>


<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<style>
    #DoctorProfile .body {
        background: -webkit-linear-gradient(left, #3931af, #00c6ff);
    }

    .emp-profile {
        padding: 3%;
        margin-top: 3%;
        margin-bottom: 3%;
        border-radius: 0.5rem;
        background: #fff;
    }

    .profile-img {
        text-align: center;
    }

        .profile-img img {
            width: 70%;
            height: 100%;
        }

        .profile-img .file {
            position: relative;
            overflow: hidden;
            margin-top: -20%;
            width: 70%;
            border: none;
            border-radius: 0;
            font-size: 15px;
            background: #212529b8;
        }

            .profile-img .file input {
                position: absolute;
                opacity: 0;
                right: 0;
                top: 0;
            }

    .profile-head h5 {
        color: #333;
    }

    .profile-head h6 {
        color: #0062cc;
    }

    .profile-edit-btn {
        border: none;
        border-radius: 1.5rem;
        width: 70%;
        padding: 2%;
        font-weight: 600;
        color: #6c757d;
        cursor: pointer;
    }

    .proile-rating {
        font-size: 12px;
        color: #818182;
        margin-top: 5%;
    }

        .proile-rating span {
            color: #495057;
            font-size: 15px;
            font-weight: 600;
        }

    .profile-head .nav-tabs {
        margin-bottom: 5%;
    }

        .profile-head .nav-tabs .nav-link {
            font-weight: 600;
            border: none;
        }

            .profile-head .nav-tabs .nav-link.active {
                border: none;
                border-bottom: 2px solid #0062cc;
            }

    .profile-work {
        padding: 14%;
        margin-top: -15%;
    }

        .profile-work p {
            font-size: 12px;
            color: #818182;
            font-weight: 600;
            margin-top: 10%;
        }

        .profile-work a {
            text-decoration: none;
            color: #495057;
            font-weight: 600;
            font-size: 14px;
        }

        .profile-work ul {
            list-style: none;
        }

    .profile-tab label {
        font-weight: 600;
    }

    .profile-tab p {
        font-weight: 600;
        color: #0062cc;
    }
</style>

<div class="container emp-profile">
    <form action="/Booking/PatientProfile" method="post" enctype="multipart/form-data">

        @*@foreach (var patient in Model)
            {*@

        <div class="row">

            <div class="col-md-4">
                <div class="profile-img">
                    <td>
                        @Html.EditorFor(model => model.Avatar, new { htmlAttributes = new { @class = "form-control", @hidden = true } })
                        <img src="@Model.Avatar" style="width:100px;" />
                    </td>
                    <div class="file btn btn-lg btn-primary">
                        Change Photo
                        <input type="file" name="myFile" />
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h2>
                        @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                        @*@Model.FullName*@
                    </h2>

                </div>
            </div>
           
        </div>
        <br />
        <hr />
        <div class="row">

            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>User Id</label>
                            </div>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.IDPatient, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.IDPatient, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <hr />
                        <div class="row">
                            <div class="col-md-6">
                                <label>UserName</label>
                            </div>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-6">
                                <label>Password</label>
                            </div>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

                                @*<p>@Model.PhoneNumber</p>*@
                            </div>
                            <hr />
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>MatKhauNL</label>
                            </div>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.MatKhauNL, new { htmlAttributes = new { @class = "form-control" } })
                            </div>

                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                                @*<p>@Model.Email</p>*@
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone</label>
                            </div>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control"  } })
                                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })

                                
                                <hr />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="LƯU THAY ĐỔI THÔNG TIN" class="btn btn-outline-warning" />
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>

    </form>
</div>

FinalDatLong/Views/Booking/ProfileDoctor.cshtml
@model FinalDatLong.Models.Booking
@{
    ViewBag.Title = "ProfileDoctor";
    Layout = "~/Views/Shared/LayoutNavbar.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<style>
    /* Your styles here */
</style>
@using (Html.BeginForm("ProfileDoctor", "Booking", FormMethod.Post, new { id = Model.IDDoctor }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            <div class="col-4">
                <div class="profile-img">
                    <img src="@Model.Doctor.Avatar" style="width:200px; height:200px" />
                </div>

                <div class="profile-head">
                    <h3>
                        @Model.Doctor.FullName
                    </h3>
                </div>

                <div class="col-md-4">
                    <div class="profile-work">
                        <h5>Introduction: @Model.Doctor.Introduction</h5>
                        <p>Specialization: @Model.Doctor.Specialization</p>
                        <p>Email: @Model.Doctor.Email</p>
                        <p>Phone: @Model.Doctor.Phone</p>
                    </div>
                </div>
            </div>
            <div class="col-8">
                <div class="row">
                    <h3 class="text-center" style="padding: 5% 0 0 0">ĐẶT LỊCH KHÁM BỆNH</h3>


                    <div class="form-horizontal">
                        <h4>Booking</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.IDPatient, "IDPatient", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("IDPatient", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IDPatient, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IDDoctor, "IDDoctor", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("IDDoctor", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IDDoctor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Accept, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Accept)
                                    @Html.ValidationMessageFor(model => model.Accept, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Datetime, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Datetime, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Datetime, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Đặt lịch hẹn " class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
}