FinalDatLong/Controllers/ALLController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalDatLong.Controllers
{
    public class ALLController : Controller
    {
        // GET: ALL
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Contacts() 
        {
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        public ActionResult Question()
        {
            return View();
        }
        public ActionResult Service()
        {
            return PartialView();
        }
        public ActionResult Instruction()
        {
            return PartialView();
        }
    }
}

FinalDatLong/Controllers/BookingController.cs
using FinalDatLong.Models;
using SachOnline;
using System;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using System.Web.UI.WebControls;

namespace FinalDatLong.Controllers
{
    public class BookingController : Controller
    {
        // GET: Booking
        Model1 db = new Model1();
       
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Navbar()
        {
            return PartialView();
        }

        public ActionResult Footer()
        {
            return PartialView();
        }
        public ActionResult LayoutNavbar()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return PartialView();
        }
        public ActionResult NavbarDangNhap()
        {
            return PartialView();
        }
        public ActionResult SlideShow()
        {
            return PartialView();
        }
        public ActionResult Video()
        {
            return PartialView();
        }
        public ActionResult Card()
        {
            return PartialView();
        }
        public ActionResult NewBooking()
        {
            return PartialView();
        }
        //public ActionResult ProfileDoctor(int id)
        //{
        //    var doctor = db.Doctor.FirstOrDefault(n => n.IDDoctor == id);
        //    return PartialView(doctor);
        //}

        // em new booking o day 
        //Dung get o tren em khai bao get r ma thay => 2 phuong thuc cung get phai khac nhau ve ten pt hoac tham so
        //get
        //public ActionResult ProfileDoctor2(int id ,FormCollection f)
        //{
        //    //Em khai bao id ma khi goi truyen vao IDDoctor nen se ko goi method nay
        //    Booking Booking = new Booking();
        //    var doctor = db.Doctor.Find(id);

        //    if (doctor == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    if (Session["UserName"] != null)
        //    {
        //        var patient = (Patient)Session["UserName"];
        //        // Lấy thông tin hồ sơ từ cơ sở dữ liệu dựa trên IDPatient

        //        if (patient != null)
        //        {
        //            Booking.Patient = patient;
        //            Booking.IDPatient = patient.IDPatient;
        //        }
        //        else
        //        {
        //            return RedirectToAction("Error");
        //        }
        //    }

        //    Booking.IDDoctor = id;
        //    Booking.Doctor = doctor;

        //    if (ModelState.IsValid)
        //    {
        //        db.Booking.Add(Booking);
        //        db.SaveChanges();
        //    }
        //    return View();
        //}



        public static string ConverImageToBase64(string path)
        {
            using (Image image = Image.FromFile(path))
            {
                using (MemoryStream m = new MemoryStream())
                {
                    image.Save(m, image.RawFormat);
                    byte[] imageBytes = m.ToArray();

                    string base64String = "data:image/jpeg;base64," + Convert.ToBase64String(imageBytes);
                    return base64String;
                }
            }
        }


        public ActionResult PatientProfile()
        {

            if (Session["UserName"] != null)
            {
                var patient = (Patient)Session["UserName"];
                patient.MatKhauNL = patient.Password;

                if (patient != null)
                {
                    return View(patient);
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult PatientProfile(Patient model, HttpPostedFileBase myFile)
        {
           

            if (ModelState.IsValid)
            {


                if (myFile != null)
                {
                    Image img = Image.FromStream(myFile.InputStream, true, true);
                    model.Avatar = Utility.ConvertImageToBase64(img);
                }
               
                db.Patient.AddOrUpdate(model);
                db.SaveChanges();
                Session["UserName"] = model;
            }
            
            
            return View(model);
        }





    }
}

FinalDatLong/Views/Shared/Card.cshtml
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    #Card .social_icons_rounded {
        background-color: forestgreen;
        border-radius: 50%;
        height: 150px;
        width: 150px;
        margin: 0 35% 0 25%
    }

    #Card h4 {
        font-weight: bold;
        color: #00AC4F;
        margin: 5% 0 8% 0
    }

    #Card .icon {
        font-size: 90px;
        margin: 15%;
        color: aliceblue
    }

    #Card p {
        margin: 1% 10% 0 5%
    }

    #Card .social_icons_rounded:hover {
        background-color: lawngreen;
    }
</style>

<div>
    <h2 class="text-center" style="font-weight:bold; color:#00AC4F">WELCOME TO SAIGON EYE HOSPITAL SYSTEM</h2>
    <hr style="width: 5%; border: 3px solid #007810; border-radius: 5px; margin: 2% 50% 0 45%; " />

    <div id="Card" class="row">
        <div class="col-sm-12 col-md-6 col-lg-3 my-5">
            <div class="card border-0">
                <div class="card-body text-center">
                    <div class="social_icons_rounded"><i class="fa fa-user-md icon"></i> </div>
                    <h4>EXPERIENCED DOCTORS</h4>
                    <p>Our team of ophthalmologists consists of experts with a solid professional background, rich experience, and ethical values.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 my-5">
            <div class="card border-0">
                <div class="card-body text-center">
                    <div class="social_icons_rounded"><i class="fa fa-stethoscope icon"></i> </div>
                    <h4>MODERN TECHNOLOGY</h4>
                    <p>We utilize state-of-the-art medical equipment imported from the UK, the USA, and Germany.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 my-5">
            <div class="card border-0">
                <div class="card-body text-center">
                    <div class="social_icons_rounded"><i class="fa fa-balance-scale icon"></i> </div>
                    <h4>REASONABLE COST</h4>
                    <p>Transparent and clear costs for examinations, treatments, and surgeries, along with attractive support incentives.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 my-5">
            <div class="card border-0">
                <div class="card-body text-center">
                    <div class="social_icons_rounded"><i class="fa fa-building icon"></i> </div>
                    <h4>EXTENSIVE NETWORK</h4>
                    <p>A network of 10 hospitals covering from the North to the South, convenient for people across the country.</p>
                </div>
            </div>
        </div>
    </div>

</div>

FinalDatLong/Views/Shared/Contact.cshtml
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
</head>
<style>
    #contact .card:hover i, #contact .card:hover h4 {
        color: #00ff21;
    }
</style>






<section id="contact">

    <div class="container" style="color: #00AC4F">
        <h2 class="text-center" style="font-weight:bold; color:#00AC4F">GEOGRAPHICAL LOCATION</h2>
        <hr style="width: 5%; border: 3px solid #007810; border-radius: 5px; margin: 2% 50% 0 45%; " />
        <br />
        <br />
        <br />
        <div class="row mt-2">
            <div class="col col-md-12">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3916.7726638930376!2d106.67289931070428!3d10.98052468913583!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174d1085e2b1c37%3A0x73bfa5616464d0ee!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBUaOG7pyBE4bqndSBN4buZdA!5e0!3m2!1svi!2s!4v1698629469881!5m2!1svi!2s"
                        width="100%" height="450" frameborder="0" style="border:0" allowfullscreen=""></iframe>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-3 my-5">
                <div class="card border-0">
                    <div class="card-body text-center">
                        <i class="fa fa-phone fa-5x mb-3" aria-hidden="true"></i>
                        <h4 class="text-uppercase mb-5">call us</h4>
                        <p>0587944658,0123456789</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-3 my-5">
                <div class="card border-0">
                    <div class="card-body text-center">
                        <i class="fa fa-map-marker fa-5x mb-3" aria-hidden="true"></i>
                        <h4 class="text-uppercase mb-5">office loaction</h4>
                        <address>Trường Đại Học Thủ Dầu Một </address>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-3 my-5">
                <div class="card border-0">
                    <div class="card-body text-center">
                        <i class="fa fa-map-marker fa-5x mb-3" aria-hidden="true"></i>
                        <h4 class="text-uppercase mb-5">office loaction</h4>
                        <address>Trường Đại Học Thủ Dầu Một </address>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-3 my-5">
                <div class="card border-0">
                    <div class="card-body text-center">
                        <i class="fa fa-globe fa-5x mb-3" aria-hidden="true"></i>
                        <h4 class="text-uppercase mb-5">email</h4>
                        <p>21280103E0017@student.tdmu.edu.vn</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

FinalDatLong/Views/Shared/Footer.cshtml
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

<footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3" style="background-color: #00AC4F; color:aliceblue">
        <div class="container text-center text-md-start mt-5">
            <div class="row mt-3">
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <h4>
                        Website for Booking Doctor Appointments: Final project for the web programming course, using MVC, HTML, CSS, C# in Binh Duong, dated 31/10/2023.
                    </h4>
                    <img src="https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/42008041469/original/Mo9gDy2XMZLppkUw4sWCsYV-lk65HqqgQw.gif?1539077990" height="60" width="150" />
                    <hr />
                    <hr />
                    <img src="https://images.dmca.com/Badges/dmca-badge-w150-5x1-06.png?ID=7f68b1c4-15cd-4450-9f3d-a696d34ca826" height="30" width="150" />
                </div>
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <h4 class="text-uppercase fw-bold mb-4">
                        Services
                    </h4>
                    <p>
                        <a href="#!" class="text-reset">Eye Examination</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Joint Surgery</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">ENT Treatment</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Dermatology Surgery</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Radiation Therapy</a>
                    </p>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <h4 class="text-uppercase fw-bold mb-4">
                        About Us
                    </h4>
                    <p>
                        <a href="#!" class="text-reset">Our Network</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">News</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Promotions</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Equipment</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Library</a>
                    </p>
                </div>
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <h4 class="text-uppercase fw-bold mb-4">Contact</h4>
                    <p><i class="bi bi-geo-alt-fill"></i> Thu Dau Mot</p>
                    <p>
                        <i class="bi bi-envelope-at-fill"></i>
                        info@Booking.com
                    </p>
                    <p><i class="bi bi-telephone-fill"></i> +01 234 567 89</p>
                </div>
            </div>
        </div>
    </div>
</footer>
<footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3" style="background-color: #61CE70; color:aliceblue">
        <div class="container p-4 pb-0">
            <form action="">
                <div class="row">
                    <div class="col-auto mb-4 mb-md-0">
                        <p class="pt-2">
                            <strong>
                                Subscribe to our latest news and services!
                            </strong>
                        </p>
                    </div>
                    <div class="col-md-5 col-12 mb-4 mb-md-0">
                        <div class="form-outline mb-4">
                            <input type="email" id="form5Example25" class="form-control" />
                        </div>
                    </div>
                    <div class="col-auto mb-4 mb-md-0">
                        <button type="submit" class="btn btn-success ">
                            Sign Up
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</footer>
<footer class="text-center" style="background-color: #009247 ; color:aliceblue">
    <p>&copy; Booking Appointment Doctor </p>
    <p>All information provided is for reference only. Patients must visit the hospital in person for diagnosis and treatment by a doctor.</p>
</footer>

FinalDatLong/Views/Shared/LayoutNavbar.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="row">
        @Html.Action("NavbarDangNhap", "Booking")

    </div>
    <div>
        @RenderBody()
    </div>
</body>
</html>

FinalDatLong/Views/Shared/Navbar.cshtml
<link href="~/Content/Site.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<script src="~/Scripts/popper.min.js"></script>
<style>
    .nav-text {
        margin: 10px;
        display: inline-block;
        color: #000000;
    }

        .nav-text:before {
            content: '';
            height: 2px;
            background: #00ff21;
            display: block;
            transition: width 0.3s ease-in-out;
            margin: 0 auto;
        }

        .nav-text:before {
            width: 150%;
        }

        .nav-text:after {
            width: 0;
        }

        .nav-text:hover:before {
            width: 0;
        }

        .nav-text:hover:after {
            width: 100%;
        }




    h3 {
        color: #23A455;
    }

    li {
        margin: 10% 0 0 0
    }

    .btn {
        border: none; /* Remove borders */
        color: white; /* Add a text color */
        padding: 14px 28px; /* Add some padding */
        cursor: pointer; /* Add a pointer cursor on mouse-over */
    }

    .btnHotline {
        border: none; /* Remove borders */
        color: white;
        width: 100%;
        height: 10%;
    }

    .success {
        background-color: #23A455;
    }
        /* Green */
        .success:hover {
            background-color: #b6ff00;
        }

    .modal-dialog.modal-xxl {
        width: 90%; /* Điều chỉnh chiều rộng theo mong muốn */
        max-width: 80%; /* Điều chỉnh chiều rộng tối đa theo mong muốn */
        height: 90vh; /* Điều chỉnh chiều cao theo mong muốn */
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <img src="https://images.ctfassets.net/4x7ph7u3e2qj/5Y6W7JeaVCjD0udP6tFcwh/180ea8bfd38ef8f4a9feaf2b777df832/____101_-_hospital-cover.jpg" alt="..." class="img-fluid h-100">
        </div>
        <div class="col-lg-6">
            <br />
            <div class="row">

                <div class="col text-end ">
                    <!-- Nội dung ở giữa, cột 2 -->


                    @if (Session["UserName"] != null)
                    {



                        <a href="@Url.Action("PatientProfile", "Booking")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Profile <i class="bi bi-person-badge"></i>
                        </a>

                        <a href="@Url.Action("ViewFeedback","User")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            View Feedback <i class="bi bi-chat-left-dots-fill"></i>
                        </a>

                        <a href="@Url.Action("Feedback", "User", new { id = ViewBag.IDPatient })" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Feedback <i class="bi bi-chat-left-dots-fill"></i>
                        </a>

                        <a href="@Url.Action("DangXuat","User")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Log out <i class="bi bi-box-arrow-right"></i>
                        </a>


                    }
                    else
                    {

                        @*<div class="btn-group">
                <button type="button" class="btn btn-outline-success" data-bs-toggle="dropdown">
                    Profile
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="@Url.Action("PatientProfile", "Booking")">Profile</a></li>

                </ul>
            </div>*@

                        <a href="@Url.Action("DangKy","User")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Register <i class="bi bi-r-square-fill"></i>
                        </a>

                        <a href="@Url.Action("DangNhap","User")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Log In <i class="bi bi-box-arrow-in-left"></i>
                        </a>

                    }

                </div>

                <br>
            </div>
            <!-- Dòng 2 -->
            <div class="row">
                <div class="col-12">
                    <!-- Nội dung ở giữa, full width -->
                    <ul class="nav nav-inline">
                        <li class="nav-item nav-text"><a class="nav-link text-center" style="color:black" href="~/Booking/Index">Home</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("AboutUs","ALL")">About Us</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("Service","ALL")">Sevrice</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("Question","ALL")">Question</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("Instruction","ALL")">Instruction</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("Contacts","ALL")">Contact</a></li>
                    </ul>

                </div>
            </div>
        </div>
        @*<div class="col-lg-3">
            @Html.Action("NewBooking", "Booking")
        </div>*@

        <div class="col-lg-3">
            @if (Session["UserName"] != null)
            {
                @Html.Action("NewBooking", "Booking")
            }
            else
            {
                <a href="@Url.Action("DangNhap", "User")" style="border-radius: 0px; display: block;">
                    <img src="https://sonqb.com/media/2021/07/dich-vu-booking-pr-bao-sonqb.jpg" width="150%" alt="Booking Service Image" style="cursor: pointer;" onclick="redirectToLogin()"  />
                </a>

                <script>
            function redirectToLogin() {
                window.location.href = '@Url.Action("DangNhap", "User")';
            }
                </script>
            }
        </div>




    </div>
</div>

FinalDatLong/Views/Shared/NavbarDangNhap.cshtml
<link href="~/Content/Site.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<script src="~/Scripts/popper.min.js"></script>
<style>
    .nav-text {
        margin: 10px;
        display: inline-block;
        color: #000000;
    }

        .nav-text:before {
            content: '';
            height: 2px;
            background: #00ff21;
            display: block;
            transition: width 0.3s ease-in-out;
            margin: 0 auto;
        }

        .nav-text:before {
            width: 150%;
        }

        .nav-text:after {
            width: 0;
        }

        .nav-text:hover:before {
            width: 0;
        }

        .nav-text:hover:after {
            width: 100%;
        }




    h3 {
        color: #23A455;
    }

    li {
        margin: 10% 0 0 0
    }

    .btn {
        border: none; /* Remove borders */
        color: white; /* Add a text color */
        padding: 14px 28px; /* Add some padding */
        cursor: pointer; /* Add a pointer cursor on mouse-over */
    }

    .btnHotline {
        border: none; /* Remove borders */
        color: white;
        width: 100%;
        height: 10%;
    }

    .success {
        background-color: #23A455;
    }
        /* Green */
        .success:hover {
            background-color: #b6ff00;
        }

    .modal-dialog.modal-xxl {
        width: 90%; /* Điều chỉnh chiều rộng theo mong muốn */
        max-width: 80%; /* Điều chỉnh chiều rộng tối đa theo mong muốn */
        height: 90vh; /* Điều chỉnh chiều cao theo mong muốn */
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <img src="https://images.ctfassets.net/4x7ph7u3e2qj/5Y6W7JeaVCjD0udP6tFcwh/180ea8bfd38ef8f4a9feaf2b777df832/____101_-_hospital-cover.jpg" alt="..." class="img-fluid h-100">
        </div>
        <div class="col-lg-6">
            <br />
            <div class="row">

                <div class="col text-end ">
                    <!-- Nội dung ở giữa, cột 2 -->


                    @if (Session["UserName"] != null)
                    {



                        <a href="@Url.Action("PatientProfile", "Booking")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Profile <i class="bi bi-person-badge"></i>
                        </a>

                        <a href="@Url.Action("ViewFeedback","User")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            View Feedback <i class="bi bi-chat-left-dots-fill"></i>
                        </a>

                        <a href="@Url.Action("Feedback", "User", new { id = ViewBag.IDPatient })" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Feedback <i class="bi bi-chat-left-dots-fill"></i>
                        </a>

                        <a href="@Url.Action("DangXuat","User")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Log out <i class="bi bi-box-arrow-right"></i>
                        </a>


                    }
                    else
                    {

                        @*<div class="btn-group">
                <button type="button" class="btn btn-outline-success" data-bs-toggle="dropdown">
                    Profile
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="@Url.Action("PatientProfile", "Booking")">Profile</a></li>

                </ul>
            </div>*@

                        <a href="@Url.Action("DangKy","User")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Register <i class="bi bi-r-square-fill"></i>
                        </a>

                        <a href="@Url.Action("DangNhap","User")" type="button" class="btn btn-outline-success" style="border-radius:0px">
                            Log In <i class="bi bi-box-arrow-in-left"></i>
                        </a>

                    }

                </div>

                <br>
            </div>
            <!-- Dòng 2 -->
            <div class="row">
                <div class="col-12">
                    <!-- Nội dung ở giữa, full width -->
                    <ul class="nav nav-inline">
                        <li class="nav-item nav-text"><a class="nav-link text-center" style="color:black" href="~/Booking/Index">Home</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("AboutUs","ALL")">About Us</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("Service","ALL")">Sevrice</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("Question","ALL")">Question</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("Instruction","ALL")">Instruction</a></li>
                        <li class="nav-item nav-text"><a class="nav-link" style="color:black" href="@Url.Action("Contacts","ALL")">Contact</a></li>
                    </ul>

                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <a href="https://sonqb.com/media/2021/07/dich-vu-booking-pr-bao-sonqb.jpg" data-bs-toggle="modal" data-bs-target="#myModal">
                <img src="https://sonqb.com/media/2021/07/dich-vu-booking-pr-bao-sonqb.jpg" alt="..." class="img-fluid h-100">
            </a>
        </div>


        


    </div>
</div>

FinalDatLong/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script src="~/Scripts/popper.min.js"></script>
    <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
    <df-messenger intent="WELCOME"
                  chat-title="AI_Chat"
                  agent-id="60ee71fe-b280-44b4-96a0-571548eaca9a"
                  language-code="en"></df-messenger>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <div class="row">
        @Html.Action("Navbar", "Booking")
    </div>
    <br />
    <div class="row">
        @Html.Action("SlideShow", "Booking")
    </div>
    <br />
    <br />
    <br />
    <br />
    <div class="row">
        @Html.Action("Card", "Booking")
    </div>

    <div class="row">
        @Html.Action("Contact", "Booking")
    </div>
    <div class="row">
        @Html.Action("Video", "Booking")
    </div>
 
    @*<div class="row">
        @Html.Action("PatientProfile","Booking")
    </div>*@

    <div class="container body-content">

        @RenderBody()
        <hr />

    </div>
    <div class="row">
        @Html.Action("Footer", "Booking")
    </div>


</body>

</html>